name: book_verse
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_chat_core: ^2.0.0
  flutter_chat_ui: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  provider: ^6.1.5+1
  riverpod_annotation: ^2.6.1
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.1
  google_sign_in: 6.1.4
  device_preview: ^1.3.1
  sqflite: ^2.4.2
  sqflite_common_ffi:
  path: ^1.9.1
  go_router: ^17.0.1
  intl: ^0.20.2
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_generator: ^2.6.5
  stop_watch_timer: ^3.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
  assets:
    - .env
    - shorebird.yaml
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700